/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyServiceReport {
  'id' : string,
  'customerName' : string,
  'issueResolved' : boolean,
  'issueFoundByEngineer' : string,
  'nextPlanOfAction' : [] | [string],
  'machineModel' : string,
  'date' : string,
  'createdBy' : Principal,
  'contactPerson' : string,
  'mobileNumber' : string,
  'sparesRequired' : string,
  'solution' : string,
  'customerFeedback' : string,
  'travelingExpensePaid' : boolean,
  'machineSerialNo' : string,
  'warrantyStatus' : string,
  'issueDescribedByCustomer' : string,
}
export type Role = { 'admin' : null } |
  { 'engineer' : null };
export interface UserProfile {
  'username' : string,
  'name' : string,
  'role' : Role,
  'mobileNumber' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReport' : ActorMethod<[DailyServiceReport], string>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReportById' : ActorMethod<[string], [] | [DailyServiceReport]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listReports' : ActorMethod<[], Array<DailyServiceReport>>,
  'listUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'purgeLegacyReportsAndUsers' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'signupWithRole' : ActorMethod<[UserProfile, Role, [] | [string]], undefined>,
  'updateUserRole' : ActorMethod<[Principal, Role], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];