/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DailyServiceReport = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'issueResolved' : IDL.Bool,
  'issueFoundByEngineer' : IDL.Text,
  'nextPlanOfAction' : IDL.Opt(IDL.Text),
  'machineModel' : IDL.Text,
  'date' : IDL.Text,
  'createdBy' : IDL.Principal,
  'contactPerson' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'sparesRequired' : IDL.Text,
  'solution' : IDL.Text,
  'customerFeedback' : IDL.Text,
  'travelingExpensePaid' : IDL.Bool,
  'machineSerialNo' : IDL.Text,
  'warrantyStatus' : IDL.Text,
  'issueDescribedByCustomer' : IDL.Text,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'engineer' : IDL.Null });
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReport' : IDL.Func([DailyServiceReport], [IDL.Text], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReportById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DailyServiceReport)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listReports' : IDL.Func([], [IDL.Vec(DailyServiceReport)], ['query']),
  'listUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'signupWithCode' : IDL.Func([UserProfile, IDL.Text], [], []),
  'updateUserRole' : IDL.Func([IDL.Principal, Role], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DailyServiceReport = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'issueResolved' : IDL.Bool,
    'issueFoundByEngineer' : IDL.Text,
    'nextPlanOfAction' : IDL.Opt(IDL.Text),
    'machineModel' : IDL.Text,
    'date' : IDL.Text,
    'createdBy' : IDL.Principal,
    'contactPerson' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'sparesRequired' : IDL.Text,
    'solution' : IDL.Text,
    'customerFeedback' : IDL.Text,
    'travelingExpensePaid' : IDL.Bool,
    'machineSerialNo' : IDL.Text,
    'warrantyStatus' : IDL.Text,
    'issueDescribedByCustomer' : IDL.Text,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'engineer' : IDL.Null });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReport' : IDL.Func([DailyServiceReport], [IDL.Text], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReportById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DailyServiceReport)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listReports' : IDL.Func([], [IDL.Vec(DailyServiceReport)], ['query']),
    'listUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'signupWithCode' : IDL.Func([UserProfile, IDL.Text], [], []),
    'updateUserRole' : IDL.Func([IDL.Principal, Role], [], []),
  });
};

export const init = ({ IDL }) => { return []; };