/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Geolocation {
    latitude: number;
    longitude: number;
}
export interface UserProfile {
    username: string;
    name: string;
    role: Role;
    mobileNumber: string;
    email: string;
}
export interface DailyServiceReport {
    id: string;
    customerName: string;
    issueResolved: boolean;
    issueFoundByEngineer: string;
    geolocation?: Geolocation;
    nextPlanOfAction?: string;
    machineModel: string;
    date: string;
    createdBy: Principal;
    contactPerson: string;
    mobileNumber: string;
    sparesRequired: string;
    solution: string;
    customerFeedback: string;
    travelingExpensePaid: boolean;
    machineSerialNo: string;
    warrantyStatus: string;
    issueDescribedByCustomer: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Role {
    admin = "admin",
    engineer = "engineer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createReport(report: DailyServiceReport): Promise<string>;
    deleteUser(user: Principal): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPendingSignupsCount(): Promise<bigint>;
    getReportById(id: string): Promise<DailyServiceReport | null>;
    getReportsForDownload(): Promise<Array<DailyServiceReport>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listReports(): Promise<Array<DailyServiceReport>>;
    listUsers(): Promise<Array<[Principal, UserProfile]>>;
    processPendingSignups(): Promise<bigint>;
    requestApproval(): Promise<void>;
    resetToFreshApp(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    signupAdmin(profile: UserProfile, password: string): Promise<void>;
    signupWithRole(profile: UserProfile, requestedRole: Role): Promise<void>;
    updateUserRole(user: Principal, newRole: Role): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, DailyServiceReport as _DailyServiceReport, Geolocation as _Geolocation, Role as _Role, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createReport(arg0: DailyServiceReport): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(to_candid_DailyServiceReport_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(to_candid_DailyServiceReport_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingSignupsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingSignupsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingSignupsCount();
            return result;
        }
    }
    async getReportById(arg0: string): Promise<DailyServiceReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportById(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportById(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsForDownload(): Promise<Array<DailyServiceReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsForDownload();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsForDownload();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReports(): Promise<Array<DailyServiceReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReports();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReports();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async processPendingSignups(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.processPendingSignups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPendingSignups();
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async resetToFreshApp(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetToFreshApp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetToFreshApp();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async signupAdmin(arg0: UserProfile, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.signupAdmin(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signupAdmin(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async signupWithRole(arg0: UserProfile, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.signupWithRole(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0), to_candid_Role_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signupWithRole(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0), to_candid_Role_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserRole(arg0: Principal, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_Role_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_Role_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_DailyServiceReport_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyServiceReport): DailyServiceReport {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyServiceReport]): DailyServiceReport | null {
    return value.length === 0 ? null : from_candid_DailyServiceReport_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Geolocation]): Geolocation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    issueResolved: boolean;
    issueFoundByEngineer: string;
    geolocation: [] | [_Geolocation];
    nextPlanOfAction: [] | [string];
    machineModel: string;
    date: string;
    createdBy: Principal;
    contactPerson: string;
    mobileNumber: string;
    sparesRequired: string;
    solution: string;
    customerFeedback: string;
    travelingExpensePaid: boolean;
    machineSerialNo: string;
    warrantyStatus: string;
    issueDescribedByCustomer: string;
}): {
    id: string;
    customerName: string;
    issueResolved: boolean;
    issueFoundByEngineer: string;
    geolocation?: Geolocation;
    nextPlanOfAction?: string;
    machineModel: string;
    date: string;
    createdBy: Principal;
    contactPerson: string;
    mobileNumber: string;
    sparesRequired: string;
    solution: string;
    customerFeedback: string;
    travelingExpensePaid: boolean;
    machineSerialNo: string;
    warrantyStatus: string;
    issueDescribedByCustomer: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        issueResolved: value.issueResolved,
        issueFoundByEngineer: value.issueFoundByEngineer,
        geolocation: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.geolocation)),
        nextPlanOfAction: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.nextPlanOfAction)),
        machineModel: value.machineModel,
        date: value.date,
        createdBy: value.createdBy,
        contactPerson: value.contactPerson,
        mobileNumber: value.mobileNumber,
        sparesRequired: value.sparesRequired,
        solution: value.solution,
        customerFeedback: value.customerFeedback,
        travelingExpensePaid: value.travelingExpensePaid,
        machineSerialNo: value.machineSerialNo,
        warrantyStatus: value.warrantyStatus,
        issueDescribedByCustomer: value.issueDescribedByCustomer
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n21(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    name: string;
    role: _Role;
    mobileNumber: string;
    email: string;
}): {
    username: string;
    name: string;
    role: Role;
    mobileNumber: string;
    email: string;
} {
    return {
        username: value.username,
        name: value.name,
        role: from_candid_Role_n8(_uploadFile, _downloadFile, value.role),
        mobileNumber: value.mobileNumber,
        email: value.email
    };
}
function from_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    engineer: null;
}): Role {
    return "admin" in value ? Role.admin : "engineer" in value ? Role.engineer : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyServiceReport>): Array<DailyServiceReport> {
    return value.map((x)=>from_candid_DailyServiceReport_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n24(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_DailyServiceReport_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyServiceReport): _DailyServiceReport {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    name: string;
    role: Role;
    mobileNumber: string;
    email: string;
}): {
    username: string;
    name: string;
    role: _Role;
    mobileNumber: string;
    email: string;
} {
    return {
        username: value.username,
        name: value.name,
        role: to_candid_Role_n27(_uploadFile, _downloadFile, value.role),
        mobileNumber: value.mobileNumber,
        email: value.email
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    issueResolved: boolean;
    issueFoundByEngineer: string;
    geolocation?: Geolocation;
    nextPlanOfAction?: string;
    machineModel: string;
    date: string;
    createdBy: Principal;
    contactPerson: string;
    mobileNumber: string;
    sparesRequired: string;
    solution: string;
    customerFeedback: string;
    travelingExpensePaid: boolean;
    machineSerialNo: string;
    warrantyStatus: string;
    issueDescribedByCustomer: string;
}): {
    id: string;
    customerName: string;
    issueResolved: boolean;
    issueFoundByEngineer: string;
    geolocation: [] | [_Geolocation];
    nextPlanOfAction: [] | [string];
    machineModel: string;
    date: string;
    createdBy: Principal;
    contactPerson: string;
    mobileNumber: string;
    sparesRequired: string;
    solution: string;
    customerFeedback: string;
    travelingExpensePaid: boolean;
    machineSerialNo: string;
    warrantyStatus: string;
    issueDescribedByCustomer: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        issueResolved: value.issueResolved,
        issueFoundByEngineer: value.issueFoundByEngineer,
        geolocation: value.geolocation ? candid_some(value.geolocation) : candid_none(),
        nextPlanOfAction: value.nextPlanOfAction ? candid_some(value.nextPlanOfAction) : candid_none(),
        machineModel: value.machineModel,
        date: value.date,
        createdBy: value.createdBy,
        contactPerson: value.contactPerson,
        mobileNumber: value.mobileNumber,
        sparesRequired: value.sparesRequired,
        solution: value.solution,
        customerFeedback: value.customerFeedback,
        travelingExpensePaid: value.travelingExpensePaid,
        machineSerialNo: value.machineSerialNo,
        warrantyStatus: value.warrantyStatus,
        issueDescribedByCustomer: value.issueDescribedByCustomer
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    engineer: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.engineer ? {
        engineer: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
